- .ci/openshift-ci/build-root/Dockerfile
- .ci/openshift-ci/build-root/e2e-test.sh
- pom.xml
This PR is introducing a dockerfile to generate a container image to run Intersmash tests on OpenShift CI, and a shell script that would be invoked by the pipeline test workflow.
It allows for intersmash PRs to be tested against ann OpenShift 4 cluster in the OpenShift CI infra, as per the documentation at https://docs.ci.openshift.org/
Validated by https://github.com/openshift/release/pull/37965
Fix #1 
- N/A I have implemented unit tests to cover my changes
> Onboarding Intersmash on OpenShift CI

- .github/workflows/simple-build.yml
After changing the main branch protection rules to add a new job, the existing simple_build workflow doesn't work anymore.
This PR is an attempt to see whether changing the workflow definition to rename the job would solve the issue, as suggested in https://github.com/orgs/community/discussions/25219
- N/A I have implemented unit tests to cover my changes
> Renaming the simple-build workflow file and the job which doesn't run anymore

- .ci/openshift-ci/build-root/e2e-test.sh
- README.md
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/InfinispanOperatorProvisionerTest.java
- tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/IntersmashConfig.java
- tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/provision/openshift/operator/OperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/ActiveMQOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/HyperfoilOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/InfinispanOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/KafkaOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/KeycloakOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/WildflyOperatorProvisioner.java
This PR implements the changes requested by #23 so that a Operator based provisioner package manifest can be configurable.
Here we also enable `InfinispanOperatorProvisionerTest`(as part of #21) to verify the changes.
Fix #23 
> [issue 23] - Operator provisioning configurable package manifest

- .ci/openshift-ci/build-root/e2e-test.sh
- README.md
- global-test.properties
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/ActiveMQOperatorProvisionerTest.java
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/HyperfoilOperatorProvisionerTest.java
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/InfinispanOperatorProvisionerTest.java
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/KafkaOperatorProvisionerTest.java
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/KeycloakOperatorProvisionerTest.java
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyOperatorProvisionerTest.java
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/operator/OperatorSubscriptionTestCase.java
- tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/IntersmashConfig.java
- tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/junit5/IntersmashExtension.java
- tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/provision/Provisioner.java
- tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/provision/openshift/operator/OperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/WildflyOperatorProvisioner.java
Enabling the Wildfly operator based provisioner test in the Intersmash testsuite.
There isn't a WildFly Operator image available on OpenShift operator hub, hence here we're using the one on [Operatorhub.io](https://operatorhub.io/operator/wildfly).
For this reason we leverage the following properties in global-test.properties:
* `intersmash.wildfly.operators.catalog_source`
* `intersmash.wildfly.operators.index_image`
* `intersmash.wildfly.operators.package_manifest`
So that Intersmash will configure a custom catalog source for us and let the community operator be deployed.
Part of #21 
> [issue 21] - Enabling WildFlyOperatorProvisionerTest

- .ci/openshift-ci/build-root/e2e-test.sh
- README.md
- global-test.properties
- tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/IntersmashConfig.java
- tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/provision/openshift/operator/OperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/ActiveMQOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/HyperfoilOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/InfinispanOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/KafkaOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/KeycloakOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/WildflyOperatorProvisioner.java
Introducing the new property `intersmash.operators.*.channel` that allows for externalized configuration of a given Operator desired channel to override the default one.
Fix #26 
> [issue 26] - Enabling Operator provisioner desired channel configuration

- deployments/openshift-jakarta-sample-standalone/pom.xml
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/WildflyImageOpenShiftProvisioner.java
Minor change into the codebase to use predefined string constant. Fix for build with Maven 3.9+ by removing of the duplicate version properties in the sample deployment project.
> Minor fixes

- pom.xml
- tools/intersmash-tools-core/pom.xml
- tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/provision/openshift/operator/OperatorProvisioner.java
Here we proposa a fix for the WIldyOperatorProvisioner, or actually the OperatorProvisioner itself, that fails occasionally when pulling the list of package manifests from a community catalog source, e.g.: quay.io/operatoruhubio/catalog.
The fix introducies a retry policy when listing community operators package manifests.
Fix #39 
> [issue 39] - Fix WildFlyOperatorTest intermittent failure

- global-test.properties
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyImageProvisionerTestCase.java
- tools/intersmash-tools-provisioners/pom.xml
- tools/intersmash-tools-provisioners/src/main/resources/filtered/intersmash-tools-provisioners.properties
This enables the WildFlyImageProvisioner test which verifies that a Wildfly applicatin image can be built out of a Wildfly Maven plugin based project, which is pulled by the executing pod and then built into an image first by using the Wildfly builder image and thenn by applying the resulting deployiment onto a WildFly runtime image. 
Part of #21 
> [issue 21] - Enabling WildflyImageProvisionerTest

- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/OpenShiftProvisionerTestBase.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/WildflyImageOpenShiftProvisioner.java
In case that application doesn't define the `CLI_LAUNCH_SCRIPT` environment property, let's define it automatically. This can prevent somebody to forget to define this variable in server provisioning.
> CLI_LAUNCH_SCRIPT defined automatically if `getCliScript` non-empty

- README.md
- pom.xml
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyTargetServerTestCase.java
Here we enable the `WildflyTargetServerTestCase` which uses a `WildflyImageOpenShiftApplication` provisioned by a `WildflyImageOpenShiftProvisioner`, similarly to what `WildflyImageProvisionerTestCase` does but using a pre-built deployment instead of a Git repo as the source for the s2i process.
Part of #21 
> Enabling the WildflyTargetServerTestCase

- global-test.properties
- pom.xml
- testsuite/pom.xml
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/KeycloakRealmImportOperatorProvisionerTest.java
- tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/provision/openshift/operator/resources/Subscription.java
- tools/intersmash-tools-provisioners/pom.xml
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/application/openshift/KafkaOperatorApplication.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/ActiveMQOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/HyperfoilOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/InfinispanOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/KafkaOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/KeycloakOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/KeycloakRealmImportOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/WildflyOperatorProvisioner.java
- tools/intersmash-tools-provisioners/src/main/java/org/keycloak/k8s/v2alpha1/KeycloakRealmImportOperatorKeycloakList.java
- tools/intersmash-tools-provisioners/src/main/java/org/keycloak/k8s/v2alpha1/KeycloakRealmImportOperatorRealmImportList.java
We need to bump Fabric8 Kubernetes client dependencies, e.g.: latest java-generator(from CRD) features require breking changes in the kubernetes model.
~This PR uses an XTF snapshot which is built from the following proposal for moving XTF to kubernetes-client 6.7.2 as well: https://github.com/RoyalKarma/xtf/pull/1~
This PR is using the following snapshots:
* XTF v. `0.31-update_kn_client-SNAPSHOT` snapshots, based on https://github.com/xtf-cz/xtf/pull/532
* `io.strimzi:api:0.37.0-SNAPSHOT` from https://oss.sonatype.org/service/local/repositories/snapshots/content/io/strimzi/strimzi/0.37.0-SNAPSHOT/ 
> [Upgrade Fabric8 Kubernetes Client to 6.8.1] - Solving broken APIs changes

- demos/pom.xml
- demos/ws-bootable-jar-example/README.md
- demos/ws-bootable-jar-example/jaxws/pom.xml
- demos/ws-bootable-jar-example/jaxws/scripts/property.cli
- demos/ws-bootable-jar-example/jaxws/src/main/java/org/jboss/jaxws/Endpoint.java
- demos/ws-bootable-jar-example/jaxws/src/main/java/org/jboss/jaxws/EndpointImpl.java
- demos/ws-bootable-jar-example/jaxws/src/main/webapp/WEB-INF/jboss-web.xml
- demos/ws-bootable-jar-example/jaxws/src/test/java/org/jboss/jaxws/SoapWildflyBootableOpenShiftJarApplication.java
- demos/ws-bootable-jar-example/jaxws/src/test/java/org/jboss/jaxws/SoapWildflyBootableOpenShiftJarTest.java
- demos/ws-bootable-jar-example/jaxws/src/test/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
- demos/ws-bootable-jar-example/jaxws/src/test/resources/logback.xml
- demos/ws-bootable-jar-example/pom.xml
- pom.xml
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/HyperfoilOperatorProvisionerTest.java
A jaxws test example
(fix https://github.com/Intersmash/intersmash/issues/82)
> Jaxws bootable jar test

- pom.xml
Bumping jGit dependencies to a version that solves [CVE-2023-4759](https://github.com/advisories/GHSA-3p86-9955-h393)
> CVE-2023-4759 - bump jgit to 6.6.1.202309021850-r

- deployments/intersmash-deployments-shared/intersmash-deployments-shared-wildfly/pom.xml
- deployments/openshift-jakarta-sample-standalone/pom.xml
EAP 8 deplopyments that are used by the test suite should be built by adding the channel locatin to the EAP Maven plugin configuration.
> Use EAP 8 channels in EAP Maven Plugin configuration

- README.md
Adding the Application descriptor building block documentation to the main README file 
> Add application descriptor documentation to README

- pom.xml
https://github.com/xtf-cz/xtf/compare/0.31...0.32
it contains only one fix for regression in DeploymentConfig and BuildConfig update
> bump XTF to 0.32

- pom.xml
Manually bump logback-classic to 1.2.13 to resolve the [security alert](https://github.com/Intersmash/intersmash/security/dependabot/4).
Fix https://github.com/Intersmash/intersmash/security/dependabot/4
> [CVE-2023-6378] - Manually bump logback-classic to 1.2.13

- .ci/openshift-ci/build-root/e2e-test-periodic.sh
- .ci/openshift-ci/build-root/e2e-test.sh
> [issue 136] - Adding a specific e2e script for the OpenShift CI periodic prow job (and minor fixes/cleanup)

- provisioners/src/main/java/org/jboss/intersmash/provision/openshift/BootableJarImageOpenShiftProvisioner.java
Fixes https://github.com/Intersmash/intersmash/issues/143
> Mount secrets into bootable jar container in BootableJarImageOpenShiftProvisioner

- global-test.properties
Fix #161 
- **N/A** - I have implemented unit tests to cover my changes
> [issue 161] - Use the :centos7 tag for PostgreSql and MySql images

- examples/wildfly-keycloak-saml-adapter/pom.xml
- global-test.properties
- testsuite/deployments/openshift-jakarta-sample-standalone/pom.xml
- testsuite/deployments/wildfly-shared/pom.xml
- testsuite/integration-tests/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/OpenShiftProvisionerTestBase.java
- testsuite/integration-tests/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/ProvisionerCleanupTestCase.java
> Bump WildFly/EAP bits defaults to latest

- provisioners/pom.xml
- provisioners/src/main/java/org/jboss/intersmash/provision/helm/wildfly/WildFlyHelmChartReleaseAdapter.java
- provisioners/src/main/java/org/jboss/intersmash/provision/helm/wildfly/WildflyHelmChartRelease.java
- provisioners/src/main/java/org/jboss/intersmash/provision/helm/wildfly/eap8/Eap8HelmChartReleaseAdapter.java
- provisioners/src/main/java/org/jboss/intersmash/provision/helm/wildfly/xp5/EapXp5HelmChartReleaseAdapter.java
- provisioners/src/main/resources/org/jboss/intersmash/provision/helm/values/schema/eap8/helm-eap8-release.json
- provisioners/src/main/resources/org/jboss/intersmash/provision/helm/values/schema/xp5/helm-xp5-release.json
- provisioners/src/test/java/org/jboss/intersmash/provision/helm/wildfly/EapHelmChartReleaseAdapterTest.java
Added Helm chart release adapter for EAP XP 5, also added build mode manipulation methods to other Helm chart release adapters.
Closes #179 
> Added Helm chart release adapter for EAP XP 5

- testsuite/integration-tests/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/InfinispanOperatorProvisionerTest.java
Removing a test which specifically sets `.spec.service.type=cache` and changing another one in order to set `.spec.service.type=datagrid`
Fixes #190
> [issue 190] - Fix InfinispanOperatorProvisionerTest in order not to use .spec.service.type=cache and .spec.autoscale

- .github/workflows/simple-build.yml
SSIA
Closes #196
- **N/A** I have implemented unit tests to cover my changes
- **N/A** I tested my code in OpenShift
> [issue-196] - Adding dependency caching to the simple-build workflow Maven build

- docs/GETTING_STARTED.md
Improving the GETTING_STARTED.md file in order to provide a better documentation, including where to get a usable OpenShift cluster and how to configure Intersmash.
- **N/A** I have implemented unit tests to cover my changes
- **N/A** I tested my code in OpenShift
> Improve GETTING_STARTED.md
