Intersmash/intersmash

- .github/workflows/build_only.yml
- .github/workflows/simple_build.yml
- deployments/intersmash-deployments-shared/intersmash-deployments-shared-wildfly/pom.xml
- deployments/openshift-jakarta-sample-standalone/pom.xml
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartOpenShiftExampleApplicaton.java
Adding a simple build GitHub Actions based CI checks workflow.
Fixes #2 
* See https://github.com/fabiobrz/intersmash/actions/runs/4459832564 for verification.
Please make sure your MR meets the following requirements:
> Add GitHub Actions based simple build workflow 

- .github/ISSUE_TEMPLATE/bug_report.md
> Update issue templates - add the bug report issue template

- .ci/openshift-ci/build-root/e2e-test.sh
- global-test.properties
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/MysqlImageTestCase.java
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/PostgreSQLImageTestCase.java
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/ProvisionerCleanupTestCase.java
Enabling the MySql and PostrgreSql provisioners tests.
Part of #21 
> Enable the MySql and PostrgreSql provisioners tests

- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/operator/OperatorSubscriptionTestCase.java
Enabling this test will verify the operator based provisioning subscription process. The test logic has been simplified by using a parametric test method and a provider.
Part of #21 
> [issue 21] - Enabling the OperatorSubscriptionTestCase tests

- tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/IntersmashConfig.java
- tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/junit5/IntersmashExecutionCondition.java
- tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/junit5/IntersmashExtension.java
Fix #60 
- [] I tested my code in OpenShift
> [issue 60] - Remove the cause triggering unwanted connections to OCP cluster from IntersmashConfig

- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesOpenShiftExampleApplicaton.java
- testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/WildflyHelmChartExistingValuesProvisionerTest.java
- testsuite/src/test/resources/org/jboss/intersmash/testsuite/provision/openshift/helm-values.yaml
- testsuite/src/test/resources/org/jboss/intersmash/testsuite/provision/openshift/wildfly-helm-values.yaml
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/application/openshift/helm/HelmChartOpenShiftApplication.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/helm/HelmChartOpenShiftProvisioner.java
The ability to use Helm {{--set}} overrides, and an example of using those AND an existing Helm values file
Fix #79 
> The ability to use Helm {{--set}} overrides

- deployments/intersmash-deployments-shared/intersmash-deployments-shared-wildfly/pom.xml
- deployments/intersmash-deployments-shared/intersmash-deployments-shared-wildfly/wildfly-bootable-jar-javax/pom.xml
- deployments/openshift-jakarta-sample-standalone/pom.xml
Bumping WildFly bits to latest, for Jakarta EE 8 stuff too - i.e. 26.1.2 -> 26.1.3
Fix #89 
> Bumping WildFly bits to latest

- CONTRIBUTING.md
- README.md
- tools/intersmash-tools-core/src/main/java/org/jboss/intersmash/tools/IntersmashConfig.java
- tools/intersmash-tools-provisioners/README.md
> [issue 9] - Simplify and improve project docs

- pom.xml
Provide up-to-date list of client JVM JPMS arguments as suggested by https://access.redhat.com/articles/6956861
> Update Client JPMS arguments

- deployments/intersmash-deployments-provider/pom.xml
- deployments/intersmash-deployments-provider/src/test/java/org/jboss/intersmash/deployments/IntersmashSharedDeploymentsTest.java
- deployments/intersmash-deployments-shared/pom.xml
- deployments/pom.xml
- pom.xml
- tools/intersmash-tools-core/pom.xml
- tools/intersmash-tools-provisioners/pom.xml
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/application/openshift/RhSsoTemplateOpenShiftApplication.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/application/openshift/template/Eap7Template.java
- tools/intersmash-tools-provisioners/src/main/java/org/jboss/intersmash/tools/provision/openshift/KeycloakOperatorProvisioner.java
- tools/pom.xml
> Implement requirements for deploying to Maven central

- core/pom.xml
- examples/pom.xml
- pom.xml
- provisioners/pom.xml
- testsuite/deployments/deployments-provider/pom.xml
- testsuite/deployments/eap7-shared/pom.xml
- testsuite/deployments/pom.xml
- testsuite/deployments/wildfly-shared/pom.xml
- testsuite/integration-tests/pom.xml
- testsuite/pom.xml
> Fix deploy, sign, Javadoc and source plugins after experimenting with publishing artifacts

- README.md
> [issue 134] - Document next milestone goals

- provisioners/src/main/java/org/jboss/intersmash/application/openshift/Eap7ImageOpenShiftApplication.java
- testsuite/integration-tests/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/ProvisionerCleanupTestCase.java
> [issue 146] - Fix Eap7ImageOpenShiftApplication

- README.md
- testsuite/deployments/deployments-provider/pom.xml
- testsuite/deployments/deployments-provider/src/main/java/org/jboss/intersmash/test/deployments/WildflyDeploymentApplicationConfiguration.java
- testsuite/deployments/deployments-provider/src/test/java/org/jboss/intersmash/test/deployments/WildflyDeploymentApplicationConfigurationTest.java
> [issue 27] - Making the Keycloak SAML Adapter feature pack version configurable for WildFly deployments

- README.md
- provisioners/src/test/java/org/jboss/intersmash/provision/ProvisionerManagerTestCase.java
- testsuite/deployments/deployments-provider/src/main/java/org/jboss/intersmash/test/deployments/WildflyDeploymentApplicationConfiguration.java
- testsuite/deployments/deployments-provider/src/test/java/org/jboss/intersmash/test/deployments/WildflyDeploymentApplicationConfigurationTest.java
> [issue 153] - Adding property to externalize the WildFly Datasources Galleon pack

- examples/ws-bootable-jar-example/jaxws/src/test/java/org/jboss/jaxws/SoapWildflyBootableOpenShiftJarApplication.java
- examples/wstrust/test/src/test/java/org/jboss/jaxws/STSWstrustOpenShiftJarApplication.java
- examples/wstrust/test/src/test/java/org/jboss/jaxws/ServiceWstrustOpenShiftJarApplication.java
- pom.xml
- provisioners/pom.xml
- provisioners/src/main/java/org/jboss/intersmash/util/maven/ArtifactProvider.java
- provisioners/src/main/java/org/jboss/intersmash/util/maven/MavenSettingsUtil.java
- testsuite/deployments/deployments-provider/pom.xml
- testsuite/deployments/deployments-provider/src/main/java/org/jboss/intersmash/test/deployments/DeploymentsProvider.java
- testsuite/deployments/pom.xml
- testsuite/integration-tests/pom.xml
Moving the Maven utils to avoid publishing test artifacts, and evaluate the best approach for deployments.
Could help in triaging #112 
> Refactoring to pull out the Maven utils for deployments from the testsuite modules into the provisioners

- provisioners/src/main/java/org/jboss/intersmash/provision/openshift/InfinispanOperatorProvisioner.java
- testsuite/integration-tests/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/InfinispanOperatorProvisionerTest.java
> Adding some reference comments to the Infinispan operator provisioner implementation and test

- CONTRIBUTING.md
- README.md
- docs/BUILDING_BLOCKS.md
SSIA 
Resolves #223 
- **N/A** I have implemented unit tests to cover my changes
- **N/A** I tested my code in OpenShift
> [issue-223] - Update project docs for 0.0.3

- pom.xml
SSIA
- **N/A** I have implemented unit tests to cover my changes
- **N/A** I tested my code in OpenShift
> Adding maven-release-plugin config

- .github/workflows/simple-build.yml
SSIA
- N/A I have implemented unit tests to cover my changes
- N/A I tested my code in OpenShift
> Remove Maven setup from GitHub workflow (simple-build.yml)

- provisioners/src/main/resources/crds/datasciencecluster.opendatahub.io_datascienceclusters.yaml
- provisioners/src/main/resources/crds/dscinitialization.opendatahub.io_dscinitializations.yaml
- provisioners/src/main/resources/crds/features.opendatahub.io_featuretrackers.yaml
- provisioners/src/main/resources/crds/services.platform.opendatahub.io_monitorings.yaml
> [issue-246] - Update Open Data Hub CRD manifests to v2.25.0

- pom.xml
Changing the distribution managment repositories to align with changes in the  JBoss org Maven repository policies.
Resolves #269 
- **N/A** - I have implemented unit tests to cover my changes
- **N/A** - I tested my code in OpenShift
> [issue 269] - Update distribution managment repositories
